---
- name: Deploy Stack 
  include_tasks: single.yml
  when: 
    - docker_stack_name is defined
    - docker_stacks is undefined

- name: Deploy Multiple stacks
  include_tasks: single.yml
  loop: "{{ docker_stacks if docker_stacks is defined else [] }}"
  loop_control:
    loop_var: stack_file_item
  vars:
    docker_stack_name: "{{ stack_file_item.docker_stack_name }}"
    docker_compose_file: "{{ stack_file_item.docker_compose_file }}"
    docker_stack_auth: "{{ stack_file_item.docker_stack_auth if stack_file_item.docker_stack_auth is defined else omit }}"
    docker_stack_environment: "{{ stack_file_item.docker_stack_environment if stack_file_item.docker_stack_environment is defined else docker_stack_global_environment if docker_stack_global_environment is defined else omit }}"
    docker_stack_remove: "{{ 'yes' if stack_file_item.docker_stack_remove is defined else docker_stack_remove if docker_stack_remove is defined else 'no' }}"
    docker_stack_reinstance: "{{ stack_file_item.docker_stack_reinstance if stack_file_item.docker_stack_reinstance is defined else omit }}"
  when: 
    - docker_stacks is defined