---
- name: "pull images for {{ docker_stack_name }}"
  command: "{{ docker_compose_binpath if docker_compose_binpath is defined else 'docker-compose' }} -f {{ docker_compose_file }} pull"
  changed_when: False

- name: "Reinstance stack {{ docker_stack_name }}"
  docker_stack:
    state: 'absent'
    resolve_image: 'always'
    name: "{{ docker_stack_name }}"
    compose:
      - "{{ docker_compose_file }}"
    with_registry_auth: "{{ docker_stack_auth if docker_stack_auth is defined else 'no' }}"
  when:
    - primarymanager is defined
    - docker_stack_reinstance is defined and docker_stack_reinstance == 'yes'
    - docker_stack_remove is undefined or docker_stack_remove != 'yes'

- name: "Deploy Docker stack {{ docker_stack_name }} on Swarm"
  docker_stack:
    state: "{{ 'absent' if docker_stack_remove is defined and docker_stack_remove == 'yes' else 'present' }}"
    resolve_image: 'always'
    name: "{{ docker_stack_name }}"
    compose:
      - "{{ docker_compose_file }}"
    with_registry_auth: "{{ docker_stack_auth if docker_stack_auth is defined else 'no' }}"
  when:
    - primarymanager is defined
    - docker_stack_remove is undefined
    - docker_stack_remove is defined and docker_stack_remove != 'yes'
  environment: "{{ docker_stack_environment if docker_stack_environment is defined else omit }}"