---
- name: "pull images for {{ docker_stack_name }}"
  command: "docker -f {{ docker_compose_file }} pull"
  changed_when: False

- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: "{{ docker_stack_name }}"
    compose:
      - "{{ docker_compose_file }}"
    with_registry_auth: "{{ docker_stack_auth if docker_stack_auth is defined else 'no' }}"
  when:
    - primarymanager is defined